<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-Q6QOCII" failures="4" tests="5" name="Test" time="26.141" errors="0" timestamp="2022-11-17T10:10:50 IST">
  <testcase classname="com.Test.Login.LoginClass" name="VerifyLogingTestWith_Valid_ID_Password" time="0.631"/>
  <testcase classname="com.Test.Login.LoginClass" name="VerifyLogingTestWith_Invalid_ID_Password" time="0.494">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/] but found [https://www.sauucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/] but found [https://www.sauucedemo.com/inventory.html]
at com.Test.Login.LoginClass.VerifyLogingTestWith_Invalid_ID_Password(LoginClass.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLogingTestWith_Invalid_ID_Password -->
  <testcase classname="com.Test.Login.LoginClass" name="VerifyLogingTestWith_Valid_ID_Invalid_Password" time="0.437">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/] but found [https://www.sauucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/] but found [https://www.sauucedemo.com/inventory.html]
at com.Test.Login.LoginClass.VerifyLogingTestWith_Valid_ID_Invalid_Password(LoginClass.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLogingTestWith_Valid_ID_Invalid_Password -->
  <testcase classname="com.Test.Login.LoginClass" name="VerifyLogingTestWith_Invalid_ID_Valid_Password" time="0.46">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/] but found [https://www.sauucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/] but found [https://www.sauucedemo.com/inventory.html]
at com.Test.Login.LoginClass.VerifyLogingTestWith_Invalid_ID_Valid_Password(LoginClass.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLogingTestWith_Invalid_ID_Valid_Password -->
  <testcase classname="com.Test.Login.LoginClass" name="VerifyLogingTestWith_Blanck_ID_Password" time="0.034">
    <failure type="java.lang.IllegalArgumentException" message="Keys to send should be a not null CharSequence">
      <![CDATA[java.lang.IllegalArgumentException: Keys to send should be a not null CharSequence
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:98)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:52)
at jdk.proxy2/jdk.proxy2.$Proxy17.sendKeys(Unknown Source)
at com.POM.All.LoginPOM.userPassName(LoginPOM.java:22)
at com.Test.Login.LoginClass.VerifyLogingTestWith_Blanck_ID_Password(LoginClass.java:70)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLogingTestWith_Blanck_ID_Password -->
</testsuite> <!-- Test -->
